### ISSUE TITLE
Does not work on OCP 3.7

### ISSUE THREAD

**Issue by LutzLange** [etsauer/rdu-consulting-demo#1]
I do get this error in my App :

Reason: Error resolving ImageStreamTag php-supply-chain-app:latest in namespace openshift: imagestreams.image.openshift.io "php-supply-chain-app" not found

**Comment by garethahealy** [comment]
as the repo has not been updated in 3years and 4.x is now out, i'd regard this as a wont-fix. @etsauer ; agree?
